# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Zhunium
email: zhuny936772@gmail.com
description: zhuny's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  zhuny

# Build settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
#pagination:
#  enabled: true
#  per_page: 3
#  offset: 2
#  permalink: '/page/page:num/'
#  title: ' - page :num'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true

############################################################
# Site configuration for the Auto-Pages feature
# The values here represent the defaults if nothing is set
#autopages:
#  # Site-wide kill switch, disable here and it doesn't run at all
#  enabled: true
#
#  # Category pages, omit entire config element to disable
#  categories:
#    # Optional, the list of layouts that should be processed for every category found in the site
#    layouts:
#      - 'autopage_category.html'
#    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
#    title: 'Posts in category :cat'
#    # Optional, the permalink for the  pagination page (:cat is replaced),
#    # the pagination permalink path is then appended to this permalink structure
#    permalink: '/category/:cat'
#    # Optional, when true logging related to category pages will be supressed.
#    silent: false
#    slugify:
#      mode: 'default'   # :cat is slugified. Modes: default, raw, pretty, ascii, latin
#      case: false       # Whether to replace all uppercase letters with their lowercase counterparts
#
#  # Collection pages, omit to disable
#  collections:
#    layouts:
#      - 'autopage_collection.html'
#    title: 'Posts in collection :coll' # :coll is replaced by the collection name
#    permalink: '/collection/:coll'
#    silent: false
#    slugify:
#      mode: 'default'   # :coll is slugified.
#      case: false
#
#  # Tag pages, omit to disable
#  tags:
#    layouts:
#      - 'autopage_tags.html'
#    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
#    permalink: '/tag/:tag'
#    silent: false
#    slugify:
#      mode: 'default'   # :tag is slugified.
#      case: false

############################################################
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
